dist: trusty
sudo: false
language: node_js

node_js:
  - node

branches:
  only:
    - master

cache:
  bundler: true
  directories:
    - node_modules # NPM packages
    - functions/node_modules

install:
  - npm set progress=false
  - npm i
  - cd functions && npm i ; cd -

script:
  - CI=true npx react-scripts test --env=jsdom
  - npm run build

after_success:
  - npx firebase deploy --token $FIREBASE_TOKEN
